# List of all services (containers) to be run
services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./backend_drf/.env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend_drf

    env_file:
      - ./backend_drf/.env.docker
    depends_on:
      - db
    volumes:
      - ./backend_drf/static:/app/static
      - ./backend_drf/media:/app/media
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_SERVER_BASE_URL: "/api/v1"

    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend


# This creates a named Docker volume to permanently store PostgreSQL data.
# Without this:
  # Database data is stored inside the container
  # If container is deleted â†’ data is lost
# With this:
  # Data is stored in a Docker-managed volume
  # Data persists even if container stops or restarts
volumes:
  postgres_data: